### ISSUE TITLE
Nonconvergence caused by Generalized-mean (GeM) Pooling？

### ISSUE THREAD

**Issue by Margrate** [mangye16/ReID-Survey#3]

**Comment by Hellomodo** [comment]
Here are some tips for debugging the nonconvergence problem:
1. Replace the self.p in GeneralizedMeanPooling as a constant 3. Train the model again, and see if the nonconvergence happens?
2. Replace the self.p in GeneralizedMeanPooling as a constant 1. Train the model again, and see if the nonconvergence happens? In this way, the GeneralizedMeanPooling degrades to a normal global average pooling operation.

**Comment by Margrate** [comment]
Thank you for your reply.  When I use normal global average pooling, it can converge normally.  Did you compare the effects of Weighted Regularization Triplet (WRT) loss and Batch Hard triplet loss?

**Comment by Hellomodo** [comment]
If it can converge normally when you use normal global average pooling, then it should also converge normally when you replace the self.p in GeneralizedMeanPooling as a constant 3. Because in this way, the GeneralizedMeanPooling is just a tradeoff between global average pooling and global max pooling. 
Or you can try whether your model can converge normally with global max pooling?

Weighted Regularization Triplet (WRT) performs a little better than Batch Hard triplet loss in our experiments.

**Comment by Margrate** [comment]
In my experiments, softmax loss + center loss + Batch Hard triplet loss is better than softmax loss+ center loss + Weighted Regularization Triplet (WRT)  loss.  Maybe my backbone is different from you.

**Comment by tomFoxxxx** [comment]
> In my experiments, softmax loss + center loss + Batch Hard triplet loss is better than softmax loss+ center loss + Weighted Regularization Triplet (WRT) loss. Maybe my backbone is different from you.

That's normal.
